#!/bin/sh 

dir=.
ge="$dir/Gradescript-Examples"
gc="$dir/Gradescript-Correct"

if [ $# -ne 1 ]; then
  echo 'usage: gradescript problem_number (1-100)' >&2
  exit 1
fi

if [ "$1" -gt 0 -a "$1" -le 100 ]; then
  enum=`echo $1 | awk '{ printf "%03d\n", $1 }'`
else
  echo 'usage: gradescript problem_number (1-100)' >&2
  exit 1
fi
  
program=main
  
if [ ! -f $program ]; then
  echo "Problem $enum is incorrect."
  echo ""
  echo "Your program $program does not exist."
  exit 0
fi

rm -f tmp-$enum-test-stdout.txt tmp-$enum-test-stderr.txt tmp-$enum-correct-stdout.txt tmp-$enum-correct-stderr.txt

if [ $program = algae ]; then
  $dir/$program `cat $ge/$enum.txt` > tmp-$enum-correct-stdout.txt
  ./$program `cat $ge/$enum.txt` > tmp-$enum-test-stdout.txt
  call="./$program "`cat $ge/$enum.txt`
else 
  $dir/$program < $ge/$enum.txt > tmp-$enum-correct-stdout.txt
  ./$program < $ge/$enum.txt > tmp-$enum-test-stdout.txt
  call="./$program < $ge/$enum.txt"
fi

out=`diff $gc/tmp-$enum-correct-stdout.txt tmp-$enum-test-stdout.txt | wc | awk '{ print $1 }'`

if [ $out != 0 ]; then
  echo "Problem $enum is incorrect."
  echo ""
  echo "TEST:"
  echo ""
  echo "$call"
  echo ""
  echo "FILES:"
  echo ""
  echo "Your standard output is in tmp-$enum-test-stdout.txt."
  echo "The correct standard output is in tmp-$enum-correct-stdout.txt."
  echo ""
  echo "Look at correct files and your files, perhaps run 'diff -y' on them, and figure out your mistake."
  echo "Please remember to delete this files when you are finished."
else 
  echo "Problem $enum is correct."
  echo ""
  echo "Test: $call" 
  rm -f tmp-$enum-test-stdout.txt tmp-$enum-test-stderr.txt tmp-$enum-correct-stdout.txt tmp-$enum-correct-stderr.txt
fi
